//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the urs_solution package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __urs_solution__MAVATTITUDECTLPARAMSCONFIG_H__
#define __urs_solution__MAVATTITUDECTLPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace urs_solution
{
  class MavAttitudeCtlParamsConfigStatics;

  class MavAttitudeCtlParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(MavAttitudeCtlParamsConfig &config, const MavAttitudeCtlParamsConfig &max, const MavAttitudeCtlParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const MavAttitudeCtlParamsConfig &config1, const MavAttitudeCtlParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, MavAttitudeCtlParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const MavAttitudeCtlParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MavAttitudeCtlParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const MavAttitudeCtlParamsConfig &config) const = 0;
      virtual void getValue(const MavAttitudeCtlParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T MavAttitudeCtlParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T MavAttitudeCtlParamsConfig::* field;

      virtual void clamp(MavAttitudeCtlParamsConfig &config, const MavAttitudeCtlParamsConfig &max, const MavAttitudeCtlParamsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const MavAttitudeCtlParamsConfig &config1, const MavAttitudeCtlParamsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, MavAttitudeCtlParamsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const MavAttitudeCtlParamsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MavAttitudeCtlParamsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const MavAttitudeCtlParamsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const MavAttitudeCtlParamsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, MavAttitudeCtlParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, MavAttitudeCtlParamsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<MavAttitudeCtlParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(MavAttitudeCtlParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("roll_kp"==(*_i)->name){roll_kp = boost::any_cast<double>(val);}
        if("roll_ki"==(*_i)->name){roll_ki = boost::any_cast<double>(val);}
        if("roll_kd"==(*_i)->name){roll_kd = boost::any_cast<double>(val);}
        if("roll_r_kp"==(*_i)->name){roll_r_kp = boost::any_cast<double>(val);}
        if("roll_r_ki"==(*_i)->name){roll_r_ki = boost::any_cast<double>(val);}
        if("roll_r_kd"==(*_i)->name){roll_r_kd = boost::any_cast<double>(val);}
        if("pitch_kp"==(*_i)->name){pitch_kp = boost::any_cast<double>(val);}
        if("pitch_ki"==(*_i)->name){pitch_ki = boost::any_cast<double>(val);}
        if("pitch_kd"==(*_i)->name){pitch_kd = boost::any_cast<double>(val);}
        if("pitch_r_kp"==(*_i)->name){pitch_r_kp = boost::any_cast<double>(val);}
        if("pitch_r_ki"==(*_i)->name){pitch_r_ki = boost::any_cast<double>(val);}
        if("pitch_r_kd"==(*_i)->name){pitch_r_kd = boost::any_cast<double>(val);}
        if("yaw_kp"==(*_i)->name){yaw_kp = boost::any_cast<double>(val);}
        if("yaw_ki"==(*_i)->name){yaw_ki = boost::any_cast<double>(val);}
        if("yaw_kd"==(*_i)->name){yaw_kd = boost::any_cast<double>(val);}
        if("yaw_r_kp"==(*_i)->name){yaw_r_kp = boost::any_cast<double>(val);}
        if("yaw_r_ki"==(*_i)->name){yaw_r_ki = boost::any_cast<double>(val);}
        if("yaw_r_kd"==(*_i)->name){yaw_r_kd = boost::any_cast<double>(val);}
      }
    }

    double roll_kp;
double roll_ki;
double roll_kd;
double roll_r_kp;
double roll_r_ki;
double roll_r_kd;
double pitch_kp;
double pitch_ki;
double pitch_kd;
double pitch_r_kp;
double pitch_r_ki;
double pitch_r_kd;
double yaw_kp;
double yaw_ki;
double yaw_kd;
double yaw_r_kp;
double yaw_r_ki;
double yaw_r_kd;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_kp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_ki;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_kd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_r_kp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_r_ki;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roll_r_kd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_kp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_ki;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_kd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_r_kp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_r_ki;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_r_kd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_kp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_ki;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_kd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_r_kp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_r_ki;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_r_kd;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("MavAttitudeCtlParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const MavAttitudeCtlParamsConfig &__max__ = __getMax__();
      const MavAttitudeCtlParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const MavAttitudeCtlParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const MavAttitudeCtlParamsConfig &__getDefault__();
    static const MavAttitudeCtlParamsConfig &__getMax__();
    static const MavAttitudeCtlParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const MavAttitudeCtlParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void MavAttitudeCtlParamsConfig::ParamDescription<std::string>::clamp(MavAttitudeCtlParamsConfig &config, const MavAttitudeCtlParamsConfig &max, const MavAttitudeCtlParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class MavAttitudeCtlParamsConfigStatics
  {
    friend class MavAttitudeCtlParamsConfig;

    MavAttitudeCtlParamsConfigStatics()
    {
MavAttitudeCtlParamsConfig::GroupDescription<MavAttitudeCtlParamsConfig::DEFAULT, MavAttitudeCtlParamsConfig> Default("Default", "", 0, 0, true, &MavAttitudeCtlParamsConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_kp = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_kp = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_kp = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_kp", "double", 0, "Roll ctl PID P gain", "", &MavAttitudeCtlParamsConfig::roll_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_kp", "double", 0, "Roll ctl PID P gain", "", &MavAttitudeCtlParamsConfig::roll_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_ki = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_ki = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_ki", "double", 0, "Roll ctl PID I gain", "", &MavAttitudeCtlParamsConfig::roll_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_ki", "double", 0, "Roll ctl PID I gain", "", &MavAttitudeCtlParamsConfig::roll_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_kd = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_kd", "double", 0, "Roll ctl PID D gain", "", &MavAttitudeCtlParamsConfig::roll_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_kd", "double", 0, "Roll ctl PID D gain", "", &MavAttitudeCtlParamsConfig::roll_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_r_kp = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_r_kp = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_r_kp = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_r_kp", "double", 0, "Roll rate ctl PID P gain", "", &MavAttitudeCtlParamsConfig::roll_r_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_r_kp", "double", 0, "Roll rate ctl PID P gain", "", &MavAttitudeCtlParamsConfig::roll_r_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_r_ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_r_ki = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_r_ki = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_r_ki", "double", 0, "Roll rate ctl PID I gain", "", &MavAttitudeCtlParamsConfig::roll_r_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_r_ki", "double", 0, "Roll rate ctl PID I gain", "", &MavAttitudeCtlParamsConfig::roll_r_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_r_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_r_kd = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_r_kd = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_r_kd", "double", 0, "Roll rate ctl PID D gain", "", &MavAttitudeCtlParamsConfig::roll_r_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("roll_r_kd", "double", 0, "Roll rate ctl PID D gain", "", &MavAttitudeCtlParamsConfig::roll_r_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_kp = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_kp = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_kp = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_kp", "double", 0, "Pitch ctl PID P gain", "", &MavAttitudeCtlParamsConfig::pitch_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_kp", "double", 0, "Pitch ctl PID P gain", "", &MavAttitudeCtlParamsConfig::pitch_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_ki = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_ki = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_ki", "double", 0, "Pitch ctl PID I gain", "", &MavAttitudeCtlParamsConfig::pitch_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_ki", "double", 0, "Pitch ctl PID I gain", "", &MavAttitudeCtlParamsConfig::pitch_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_kd = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_kd", "double", 0, "Pitch ctl PID D gain", "", &MavAttitudeCtlParamsConfig::pitch_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_kd", "double", 0, "Pitch ctl PID D gain", "", &MavAttitudeCtlParamsConfig::pitch_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_r_kp = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_r_kp = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_r_kp = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_r_kp", "double", 0, "Pitch rate ctl PID P gain", "", &MavAttitudeCtlParamsConfig::pitch_r_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_r_kp", "double", 0, "Pitch rate ctl PID P gain", "", &MavAttitudeCtlParamsConfig::pitch_r_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_r_ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_r_ki = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_r_ki = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_r_ki", "double", 0, "Pitch rate ctl PID I gain", "", &MavAttitudeCtlParamsConfig::pitch_r_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_r_ki", "double", 0, "Pitch rate ctl PID I gain", "", &MavAttitudeCtlParamsConfig::pitch_r_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_r_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_r_kd = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_r_kd = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_r_kd", "double", 0, "Pitch rate ctl PID D gain", "", &MavAttitudeCtlParamsConfig::pitch_r_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("pitch_r_kd", "double", 0, "Pitch rate ctl PID D gain", "", &MavAttitudeCtlParamsConfig::pitch_r_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_kp = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_kp = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_kp = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_kp", "double", 0, "Yaw ctl PID P gain", "", &MavAttitudeCtlParamsConfig::yaw_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_kp", "double", 0, "Yaw ctl PID P gain", "", &MavAttitudeCtlParamsConfig::yaw_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_ki = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_ki = 0.001;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_ki", "double", 0, "Yaw ctl PID I gain", "", &MavAttitudeCtlParamsConfig::yaw_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_ki", "double", 0, "Yaw ctl PID I gain", "", &MavAttitudeCtlParamsConfig::yaw_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_kd = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_kd = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_kd", "double", 0, "Yaw ctl PID D gain", "", &MavAttitudeCtlParamsConfig::yaw_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_kd", "double", 0, "Yaw ctl PID D gain", "", &MavAttitudeCtlParamsConfig::yaw_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_r_kp = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_r_kp = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_r_kp = 200.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_r_kp", "double", 0, "Yaw rate ctl PID P gain", "", &MavAttitudeCtlParamsConfig::yaw_r_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_r_kp", "double", 0, "Yaw rate ctl PID P gain", "", &MavAttitudeCtlParamsConfig::yaw_r_kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_r_ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_r_ki = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_r_ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_r_ki", "double", 0, "Yaw rate ctl PID I gain", "", &MavAttitudeCtlParamsConfig::yaw_r_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_r_ki", "double", 0, "Yaw rate ctl PID I gain", "", &MavAttitudeCtlParamsConfig::yaw_r_ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_r_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_r_kd = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_r_kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_r_kd", "double", 0, "Yaw rate ctl PID D gain", "", &MavAttitudeCtlParamsConfig::yaw_r_kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr(new MavAttitudeCtlParamsConfig::ParamDescription<double>("yaw_r_kd", "double", 0, "Yaw rate ctl PID D gain", "", &MavAttitudeCtlParamsConfig::yaw_r_kd)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MavAttitudeCtlParamsConfig::AbstractGroupDescriptionConstPtr(new MavAttitudeCtlParamsConfig::GroupDescription<MavAttitudeCtlParamsConfig::DEFAULT, MavAttitudeCtlParamsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<MavAttitudeCtlParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<MavAttitudeCtlParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    MavAttitudeCtlParamsConfig __max__;
    MavAttitudeCtlParamsConfig __min__;
    MavAttitudeCtlParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const MavAttitudeCtlParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static MavAttitudeCtlParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &MavAttitudeCtlParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const MavAttitudeCtlParamsConfig &MavAttitudeCtlParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const MavAttitudeCtlParamsConfig &MavAttitudeCtlParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const MavAttitudeCtlParamsConfig &MavAttitudeCtlParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<MavAttitudeCtlParamsConfig::AbstractParamDescriptionConstPtr> &MavAttitudeCtlParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<MavAttitudeCtlParamsConfig::AbstractGroupDescriptionConstPtr> &MavAttitudeCtlParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const MavAttitudeCtlParamsConfigStatics *MavAttitudeCtlParamsConfig::__get_statics__()
  {
    const static MavAttitudeCtlParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = MavAttitudeCtlParamsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MAVATTITUDECTLPARAMSRECONFIGURATOR_H__
